name: Veracode Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file app/pom.xml
      working-directory: .

      
    - name: Veracode Upload and Scan
      uses: veracode/veracode-uploadandscan-action@0.2.7
      with:
        appname: 'Verademo SAQPSAQP'
        createprofile: true
        filepath: 'app/target/verademo.war'
        vid: '${{ vars.VERACODE_API_ID }}'
        vkey: '${{ vars.VERACODE_API_KEY }}'
        scanpollinginterval: 30
        scantimeout: 20
